"""empty message

Revision ID: 199ecaefb06c
Revises: e9ad068eae98
Create Date: 2025-06-08 18:16:32.915930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199ecaefb06c'
down_revision = 'e9ad068eae98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="birth_year::date")
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['planets_id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_who_live_here_fkey', type_='foreignkey')
        batch_op.drop_column('who_live_here')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_live_here', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planets_who_live_here_fkey', 'characters', ['who_live_here'], ['characters_id'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('birth_year',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
