"""empty message

Revision ID: 221b09f11786
Revises: 9c8a87ce41c4
Create Date: 2025-04-25 17:18:43.591745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221b09f11786'
down_revision = '9c8a87ce41c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_they_live_in_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['characters_id'])
        batch_op.drop_column('they_live_in')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_live_here', sa.Integer(), nullable=False))
        batch_op.drop_constraint('planets_they_live_in_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['who_live_here'], ['characters_id'])
        batch_op.drop_column('they_live_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('they_live_in', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planets_they_live_in_fkey', 'characters', ['they_live_in'], ['characters_id'])
        batch_op.drop_column('who_live_here')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('they_live_in', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_they_live_in_fkey', 'characters', ['they_live_in'], ['characters_id'])
        batch_op.drop_column('characters_id')

    # ### end Alembic commands ###
