"""empty message

Revision ID: e9ad068eae98
Revises: f5220d8829da
Create Date: 2025-05-02 19:34:59.019082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ad068eae98'
down_revision = 'f5220d8829da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('who_live_here',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
