"""empty message

Revision ID: f5220d8829da
Revises: 221b09f11786
Create Date: 2025-04-25 18:07:04.537850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5220d8829da'
down_revision = '221b09f11786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('planets_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('characters_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('favorite_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_type', postgresql.ENUM('character', 'type', name='favorite_type_enum'), autoincrement=False, nullable=False))
        batch_op.alter_column('characters_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planets_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
